#!/usr/bin/env python3
"""
Setup script to create .env file with Discogs credentials
"""

import os

def create_env_file():
    """Create .env file with Discogs credentials"""
    
    # Your Discogs application credentials
    credentials = {
        'DISCOGS_CONSUMER_KEY': 'WDwjaxApILXXiTrTBbpB',
        'DISCOGS_CONSUMER_SECRET': 'sRLerNInpEQEGTjUuhltwpVOhIJjnbVO',
        'USER_AGENT': 'WaxValue/1.0 +http://localhost:3000',
        'RATE_LIMIT_SECONDS': '1.2',
        'MAX_RETRIES': '3',
        'DEBUG': 'true'
    }
    
    env_content = "# Discogs API Credentials\n"
    env_content += "# Generated by setup-env.py\n\n"
    
    for key, value in credentials.items():
        env_content += f"{key}={value}\n"
    
    # Write to .env file
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("SUCCESS: .env file created successfully!")
    print("Your Discogs credentials are now configured:")
    print(f"   Consumer Key: {credentials['DISCOGS_CONSUMER_KEY']}")
    print(f"   Consumer Secret: {credentials['DISCOGS_CONSUMER_SECRET']}")
    print("\nYou can now start your backend server!")
    print("   Run: python main.py")

if __name__ == "__main__":
    create_env_file()
